name: TwoWorlds
version: 1.0
api-version: 1.13
main: org.lilbrocodes.twoworlds.TwoWorlds
commands:
  tw:
    description: Main command of the plugin
    usage: /tw [subcommand] [options]
    permission: twoworlds.tw
  reloadnpcconfig:
    description: Reloads the NPC configuration
    usage: /reloadnpcconfig
    permission: twoworlds.reload
permissions:
  twoworlds.reload:
    description: Allows the user to reload the NPC configuration
    default: op
